services:
  data_lake:
    container_name: mongo_data_lake
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 443:27017
    volumes:
      - data_lake:/data/db

  data_warehouse:
      container_name: mongo_data_warehouse
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - 80:27017
      volumes:
        - data_warehouse:/data/db

volumes:
  data_lake:
  data_warehouse:

# Virtual Machine
# version: '3.1'

# services:
#   mongo:
#     image: mongo
#     restart: always
#     enviroment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     ports:
#       - 80:27017
#     volumes:
#       - mongo-data:/data/db

#   metabase:
#     image: metabase/metabse:latest
#     restart: always
#     ports:
#       - 443:3000

# volumes:
#   mongo-data: